name: WandB CI/CD Bug Test

on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  job01:
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: find bug in comment
        if: contains(github.event.comment.body, '/bug') # check the comment if it contains the keywords
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/radikon/wandb-cicd/issues/ISSUE_NUMBER/labels \
          -f "labels[]=bug" -f "labels[]=enhancement"